# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Auto merge from main to production

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        ref: production
    - name: reset main
      run: |
        git fetch origin main:main
        git reset --hard main
    - name: Create pull request
      uses: peter-evans/create-pull-request@v7
      with:
        branch: production-pr
        title: Merge to product
